//! Canonical Protocol Layer
//!
//! This module defines the single shared schema that ALL three agents depend on.
//! No agent may duplicate or redefine these types.
//!
//! # Canonical Rules (enforced by code review)
//! 1. Rust is the authoritative runtime.
//! 2. All receipts use `CanonicalReceipt`.
//! 3. All hashes are SHA-256, deterministic.
//! 4. All APIs carry `ApiVersion`.
//! 5. No mock cryptography.
//! 6. No placeholder responses.
//! 7. No duplicate networking layers.
//! 8. No duplicate storage abstractions.
//! 9. No silent fallback behavior (config uses explicit defaults, not hidden magic).
//! 10. No hidden autogenerated state.

pub mod config;
pub mod logging;
pub mod receipt;
pub mod types;

pub use config::{CanonicalConfig, ConfigError};
pub use logging::{CanonicalLogEntry, LogLevel, log_error, log_info, log_warn};
pub use receipt::{CanonicalReceipt, ReceiptType, hash_json_canonical, merkle_root_from_hashes};
pub use types::{AgentId, ApiVersion, CanonicalTimestamp, DeterministicHash, SemVer};
